sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 114514
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: faust-for-myproject
    # 使用占位符，Spring Boot 启动时会自动从环境变量读取
    access-key-id: ${ALICLOUD_ACCESS_KEY_ID}
    access-key-secret: ${ALICLOUD_ACCESS_KEY_SECRET}
  redis:
    host: localhost
    port: 6379
    password: 114514
    database: 0
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}